### ISSUE TITLE
Memory leaking from shadow animation

### ISSUE THREAD

**Issue by klop** [DroidsOnRoids/MPParallaxView#2]
<img width="804" alt="screen shot 2015-11-12 at 10 14 43" src="https://cloud.githubusercontent.com/assets/8484253/11134193/c8aa0ec8-894f-11e5-9d20-6db0bc8573f7.png">

The current CAAnimationGroup approach is using kCAFillModeForwards alongside removedOnCompletion = NO. The result is that animations are repeatedly added to the layer without deallocating on completion. A fix would be to update the model layer's shadow properties alongside an animation that removes on completion.

**Comment by michaello** [comment]
Good catch! 👍
